### ISSUE TITLE
Cache is not invalidated by adding new files

### ISSUE THREAD

**Issue by kadamwhite** [mzgoddard/hard-source-webpack-plugin#102]
I've been able to consistently reproduce the bug I mentioned a while back, where I have to delete my cache in order for rebuilds to be picked up.

Steps:

1. Write an `import` call for a file that does not yet exist, and save the importing file.
2. Create the file that you just tried to `import`
3. The cached code continues to register the _new_ file as missing, even if the importing file is subsequently changed.

It takes an `rm` of the cache directory in order for the new file to be picked up.

Example reproduction can be followed [on this branch](https://github.com/bocoup/image-annotator/tree/recreate-bug) by checking out the "step1" tag, then running `npm start`, then checking out the `step2` tag.

**Comment by mzgoddard** [comment]
This is something (relating to #71) I was trying to solve previously but shelved due to build time increase. I've brought the [branch up to date](https://github.com/mzgoddard/hard-source-webpack-plugin/tree/resolve-missing-update).

To solve this the best thing I came up with previously was for hard source to inject itself into the resolvers and track every file attempted. Those attempts recorded later builds can check if the failures now succeed if so invalidating the original resolution and forcing a new build for the depending modules leading to building the previously missing module.

That works really well and the build time increase isn't that big (it has to stat check more file paths than previous hard-source versions). In part I really shelved it to not increase the complexity of hard-source as much in `0.3`. But this is something we can do for `0.4`.

**Comment by mzgoddard** [comment]
Fixed by #131. Update that updated branch and merged into master. Its part of `0.4`.
