### ISSUE TITLE
Does this remove no-longer-used build output?

### ISSUE THREAD

**Issue by trusktr** [mzgoddard/hard-source-webpack-plugin#117]
I'm trying this because I wanted "incremental builds". A requirement of many "incremental build" systems is that they not only update build output based on the current files, but they also delete output if those files would not exist on a clean re-build.

For example, if I move file `X.ts` to `Y.ts`, will my output folder still have `X.js` after running `webpack` again?

Is so, how can we prevent this?

**Comment by trusktr** [comment]
After some testing, it seems that after removing all build files, a rebuild is still much faster than first build, and it must be just replacing all the removed files from the cache.

Is this the recommended way to make sure that no-longer-existing source files have their respective build output deleted?

It seems that not having to delete the source folder would be more efficient and faster. Going to test it out to answer this question.

**Comment by trusktr** [comment]
Oh, I see, so as long as the entry point doesn't change, they have to be written to disk once rebuilt anyways.

I was accidentally thinking that this was like Babel or TypeScript compilers where they can create one output file per input file, but Webpack is always bundling the entry points, so deleting or not deleting the output files doesn't matter since they will always be written or re-written anyways.

**Comment by mzgoddard** [comment]
Yeah. Its intentional that files are reproduced. Some more steps would be needed to what not to emit.

A number of bugs have related to hard-source needing to emit files that it was failing to track. The current extract-text-webpack-plugin support is one of those. Files referred in css that gets extracted weren't being emitted. To support extract-text-webpack-plugin some rebuilding is needed, fortunately the amount is very small and mostly unnoticeable.

Even if those kinds of things weren't problems hard-source probably won't try to deduce what files can't be skipped when webpack emits.

(Its fun to see your progress over this little ticket.)
