### ISSUE TITLE
The speed of incremental build will much slower

### ISSUE THREAD

**Issue by wenkanglin** [mzgoddard/hard-source-webpack-plugin#120]
First of all, thanks to having the plugin that can be used to improve webpack build. But I find that the speed of **incremental build** will much slower since I used this plugin in the `development` environment.

## used package's version

* webpack 2.3.3
* happypack 3.0.3
* webpack-dev-middleware 1.10.1
* webpack-hot-middleware 2.18.0
* hard-source-webpack-plugin 0.3.11

## issue details

If I don't use the `hard-source-webpack-plugin`, the time of webpack incremental build is **300ms~800ms**. When I add this plugin, the time is **1100ms~2300ms**. It's too slow !!

This is the plugin's config:

```
new _hardSourceWebpackPlugin({
  cacheDirectory: _cache,
  recordsPath: _path.resolve(_cache, 'records.json'),
  configHash: webpackConfig => _hash(webpackConfig),
  environmentHash: () => _hash(require('../../package.json'))
})
```

I'm not sure if it is possible to slove my problem ?

**Comment by Brooooooklyn** [comment]
we have the same problem

**Comment by phyllisstein** [comment]
Same thing here. Build times with the `hard-source` cache dropped from 29s to 4s when running through the Gulp CLI, but when running through HMR they hover around 20s. Here's my config for the plugin:

```js
    new HardSourcePlugin({
      cacheDirectory: path.resolve('.cache/hardsource/[confighash]'),
      configHash (webpackConfig) {
        return hash(webpackConfig)
      },
      environmentHash: {
        directories: [
          'node_modules',
        ],
        files: [
          'package.json',
          'yarn.lock',
        ],
        root: process.cwd(),
      },
      recordsPath: path.resolve('.cache/hardsource/[confighash]/records.json'),
    }),
```

In any event, injecting it conditionally when I'm not doing a hot build should help static builds a lot, which is great!

**Comment by mihaigeorge** [comment]
My workaround would be to manually disable the plugin after the development build, so it doesn't affect the watch rebuild. I am doing something like this, but most probably it has already been register, because it is not disabled:

`const devMiddleware = require('webpack-dev-middleware')(compiler, {
        publicPath  : webpackConfig.output.publicPath,
        contentBase : paths.client(),
        hot         : false,
        quiet       : config.compiler_quiet,
        noInfo      : config.compiler_quiet,
        lazy        : false,
        stats       : config.compiler_stats
    });

    app.use(devMiddleware);

    // Manually disable HardSourcePlugin after compile step
    devMiddleware.waitUntilValid(() => {
        for (var i = compiler.options.plugins.length - 1; i >= 0; i--) {
            var plugin = compiler.options.plugins[i];
            if (plugin.constructor && plugin.constructor.name == 'HardSourceWebpackPlugin') {
                compiler.options.plugins[i] = null;
            }
        }
    })` 

Does anybody know how I can remove it on the fly?

**Comment by mzgoddard** [comment]
I ran into this symptom recently and the cause for me was context dependencies. If you are using context dependencies make sure they do not include node_modules in the nested directories from there. Webpack's context dependencies considers all directories and files recursively. If node_modules is in there webpack walks your entire node_modules to detect any changes. hard-source replicates this behaviour so it can support how context dependencies work to make sure changes are correctly reflected.

The short of this: if this cause is creating your symptoms, hard-source could detect it and warn you (something I want to add), but it can't really fix it. You need to remove any context dependencies containing node_modules.

I think the most common appearance of this will be if you `require.context` the root of your project. Naturally any really deep folder will create this issue.

-----

@mihaigeorge Removing plugins after they've connect to the Compiler is really tough. A simple plugin looks like this:

```js
class Plugin {
  apply(compiler) {
    compiler.plugin("compile", () => console.log('webpack's starting!'));
  }
}
```

Plugin's you could say are made up of smaller plugin hook handles. This example handles the `"compile"` hook which is a really early one in webpack. To remove its effect you need to remove each of the handles. And most of the time these handles are implemented as anonymous functions with no apparent reflective connection to where they came from. If you analyze the produced webpack compiler you could figure out the indices of these handles in where webpack stores them and remove them. Or like `.toString()` the functions and look for source parts.

In the case of hard-source, something I'd try would be to create a second compiler but without the hard-source plugin. You'll use the `compiler.cache` from the first compiler in the second. One of the tricky things hard-source solves is serializing and deserializing the cache (this isn't done directly by hard-source but the end result is similar). The cache contains a lot of circular references. But since hard-source helps rebuild the cache in the first compiler. The cache is all set up in memory. Give it to the second compiler and let it take over.

There may be some issues I'm not thinking of, mostly relating to extra validation checks hard-source makes on rebuilds, but that may well work.

-----

Related to all this I'm working on `v0.4` which is going to contain a hook on the compiler for hard-source logging. You could use that to silence any of its output if you want. I'm more interested in extending what hard-source logs, especially info like what modules are invalidated and why, or stats like what parts are taking how long and how many nested items are in a context dependency. This way for this and other bugs, we can log that info to the console or to a file and that'll be a big help to figuring out these black box issues.

-----

By the way, thank you @wenkanglin @Brooooooklyn @phyllisstein and @mihaigeorge for taking your time to report this issue and drop information you've found or things you tried.

**Comment by mzgoddard** [comment]
I think hard-source version `0.5.8` is in a much better position in regards to this. Will keep looking for more improvements naturally.
