### ISSUE TITLE
Css is not exported when recompile with extract-css-chunks-webpack-plugin

### ISSUE THREAD

**Issue by Crazymax11** [mzgoddard/hard-source-webpack-plugin#158]
The first build with `hard-source-webpack-plugin` and `extract-css-chunks-webpack-plugin` bundles both js and css.
But the second build bundles only js.

-----
deps.
"extract-css-chunks-webpack-plugin": "^2.0.8"
"hard-source-webpack-plugin": "^0.4.9",
 "webpack": "^3.3.0"

**Comment by Crazymax11** [comment]
related links:
extrac css plugin issue: https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/15
repo with reproduce steps from issue above: https://github.com/phyllisstein/css-chunks-hard-source

**Comment by faceyspacey** [comment]
Does hard-source work nicely with regular extract-text-webpack-plugin?

All I'm doing is creating multiple css chunks, adding them assets like this:

```js
compilation.assets[file] = stylesheet;
chunk.files.push(file);
```

And in development, I'll do some simple string replacement on all the modules to make HMR work;

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/index.js#L296

@Crazymax11 one thing to test would be to not do the HMR work I just linked. Can you try setting that to false in your `node_modules` folder to see if that solves the problem. If it doesn't, then we have better focus on the problem, which would be related to the above code i pasted, which comes from here:

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/index.js#L311

**Comment by faceyspacey** [comment]
...the thing is nobody used extract-text-webpack-plugin in development before, it was solely a production thing. So my guess is ETWP has the same problem. 

Either way, @Crazymax11 if you give the original ETWP a try, we'll have even further focus on the problem--and the problem is ETWP likely will never work nicely with hard-source. We'll just have to wait until Webpack's "master plan" for CSS unfolds, as per:

medium.com/faceyspacey/webpacks-import-will-soon-fetch-js-css-here-s-how-you-do-it-today-4eb5b4929852

**Comment by mzgoddard** [comment]
Pruning old issues.

I am not planning to directly support this in hard-source. A plugin following extract-text's behaviour in hard-source could be easily duplicated and posted to npm to support this.
