### ISSUE TITLE
Use with Circleci

### ISSUE THREAD

**Issue by fernandops26** [mzgoddard/hard-source-webpack-plugin#168]
The increase of performance also is possible in Circleci?

**Comment by vshjxyz** [comment]
Confirming that 
```yml
cache_directories:
  - node_modules/.cache/hard-source
```
does make circle save the folder but, even if it restores it in the next build, hard-source will ignore it and will recreate the cache under another hashed folder

**Comment by Crazymax11** [comment]
hard-source use modified date to create cache key.
git dont stores mtime of files and git clone set current timestamp as mtime so hard-source thinks that you updated files.
in our CI we call `find -type f -exec touch -t 201710111436 {} +` before build

**Comment by mzgoddard** [comment]
@fernandops26 It should work on CircleCI or other CIs. The default cache directory includes a hash version of the webpack config. If a property in that changes every CI build, that'll make a new cache. Also builds need to use frozen dependencies through `package-lock.json` or `yarn.lock`.

`hard-source` hasn't used file times for determining overall cache validity since last December.

**Comment by stereokai** [comment]
@mzgoddard I can confirm it is not working on CircleCI (I won't be able to test it with another CI). Can you please advise? Thanks

**Comment by mzgoddard** [comment]
Pruning old issues.
