### ISSUE TITLE
Hash webpack config instead of webpack config file

### ISSUE THREAD

**Issue by thangngoc89** [mzgoddard/hard-source-webpack-plugin#17]
As noted in the readme.md, we need to use different folders for different webpack environments. With phenomic, we have many configs that can change webpack build result so we decided to hash the whole config object and use it as the folder name. 

See our implementation here https://github.com/MoOx/phenomic/blob/master/src/_utils/webpackHardCache/webpack.js

What do you think about implemented it in the core?

**Comment by mzgoddard** [comment]
I like the idea of appending the hash to the cache-directory. I might include that in plugin. Probably as some syntax to the cacheDirectory, like `cacheDirectory: 'hard-source-cache/[hash]` like webpack lets you do with `output.path`.

Along with that I'd probably also let you include some kind of salt to the hash HardSource builds with `env-hash` to build the directory hash. In that way you could include your webpack config hash.

I'm very hesitant to include the webpack config hash feature itself in HardSource. Worried about teams that may have configs that would not deterministically generate a hash because of some runtime calculation (like including Date.now() in the config) or other non-deterministic value. Building this config hash would need to project specific so I'll leave it to be done through the salt option I'd add.

**Comment by mzgoddard** [comment]
@thangngoc89 Thank you for opening this issue by the way. I appreciate all the things you and @MoOx have been bringing up.

**Comment by thangngoc89** [comment]
Sounds good. Thanks :D . 

>  (like including Date.now() in the config) 

cc @MoOx 

We need to warn this to users. This probably the worst case.

**Comment by MoOx** [comment]
@thangngoc89 People will see a message like this

```
Environment has changed (node_modules or configuration was updated).
HardSourceWebpackPlugin will reset the cache and store a fresh one.
```

So they might say "oh there is a problem somewhere".

**Comment by thangngoc89** [comment]
@MoOx They won't see that if they uses `Date.now()`. Because we are hashing the config object, hardSourceWebpack will always get a new folder to work with.

**Comment by MoOx** [comment]
Han. True.
