### ISSUE TITLE
Does not seems to work with webpack dllplugin

### ISSUE THREAD

**Issue by MoOx** [mzgoddard/hard-source-webpack-plugin#18]
I am trying to improve performance by using your awesome plugin and at the same time webpack [dllplugin](https://webpack.github.io/docs/list-of-plugins.html#dllplugin).
But from my tests, when dllplugin (and dllpluginreference) are used, it take the same time as if this hard-source plugin was not enabled!
Some pseudo bench
- nothing: around 20s
- hard source: around 5s
- dllplugin: around 10s
- hard source + dll plugin: around 10s too ! => looks like your plugin is not enabled in this case

Any idea on this?

**Comment by mzgoddard** [comment]
Just to clarify is that the build time with `DllPlugin` or `DllReferencePlugin`?

Assuming `DllPlugin`, I'm not immediately sure what would be limiting HardSource's impact.

Assuming `DllReferencePlugin`, HardSource can't improve much for the modules delegated by the DllReferencePlugin. The ReferencePlugin uses `DelegatedModule`s instead of the `NormalModule`s that HardSource caches. If we added caching of `DelegatedModules`s I don't think it'd change the amount of time spent much, `DelegatedModule` is pretty light on work, they most likely do far less work than HardSource's HardModule. I'd wonder if the dependency to the module contained in the dll could be causing unnecessary rebuilds of the `NormalModule`s. I'll look at that but I'm doubtful as it should be a normal `CommonJsRequireDependency` (or `HarmonyImportDependency` or `AMDRequireDependency`).

Last thing I'm curious about is how you are using the dll source. Is it another script tag in your html or are you prepending it to your chunk during the webpack build? The latter could be adding time, enough to hide that HardSource is providing a benefit. If so I'd set noParse to excluding the dll from parsing. That would save a lot of time considering its probably a large file. After that there'd be a small amount additional time spent building the resulting chunk and emitting it. (Mostly building the chunk I'd guess.)

**Comment by mzgoddard** [comment]
Oh, so I looked at HardSource + Dll. Check your manifest. My manifest on the first build was correct, but the later build wasn't. I have fix inbound, its because a function on NormalModule wasn't exposed on HardModule that results in the dll building but the manifest being empty.

As this effects the dll build on the second run it'd cause the reference build to revert to using just HardModule's. If the reference build uses the first run of the dll build you should see the DllReferencePlugin taking proper effect.

**Comment by MoOx** [comment]
The issue I am facing is with `DllReferencePlugin`. I am using it via script tag to avoid webpack again on this file.

Stuff generated by `DllPlugin` seemed to look good.

**Comment by MoOx** [comment]
Will take a second look when I get some time.

**Comment by mzgoddard** [comment]
@MoOx have you been able to take a second look? I tested some myself and for `DllReferencePlugin` it is working for me.

**Comment by MoOx** [comment]
With my last test it was "working" but perf were not improved at all (your plugin: 2s, your plugin + dllreference: 12s).

**Comment by mzgoddard** [comment]
@MoOx is there a branch of Phenomic I can checkout relating to this? I have a few working test repos with DllPlugin and DllReferencePlugin that experience a speed up with the Reference plugin and HardSource together. I haven't been able to reproduce a slow down with the two. Until then I'm not sure I can move this further.

**Comment by DavidWells** [comment]
@moox lol wish I saw this thread. Just tried to implement this myself.

Was the conclusion that DLL won't work with hard source?

**Comment by MoOx** [comment]
Sorry I didn't take time to continue on this since I am pretty happy with the current state of this plugin. DLL plugins involve too much effort from the user configuration with a really small benefit at the end. Not sure I will try again on this. Will take a look if I still have my git stash somewhere :)

**Comment by mzgoddard** [comment]
@MoOx I finally figured out what your experiencing here. HardSource has a safety mechanism to invalidate modules when there cached dependencies are invalid. But HardSource doesn't yet understand dependencies that lead to DelegatedModules used by DllReferencePlugin. So when a cached module depends on a DelegatedModule its always being invalidated. The end result is Modules depending on a module in a DLL will be cached and in the next run invalidated, leading to a rebuild of that Module. Modules in the same run that don't depend on modules in the DLL will not be invalidated and will use the previously cached version.

Now I can finally fix this issue.
