### ISSUE TITLE
Error: Module did not self-register.

### ISSUE THREAD

**Issue by beckend** [mzgoddard/hard-source-webpack-plugin#19]
Import/require this module yields this, I'm just wondering - am I doing something wrong?

**Comment by mzgoddard** [comment]
@backend Is there any other info you can give me? What plugins (and their versions) are you using? What loaders are you using? webpack 1 or 2? node version?

If you can write a test or a simple mock project that produces this error that would be really helpful. (Or if its an public project link to it)

**Comment by beckend** [comment]
The project is huge and closed, but I will create a repo to try to reproduce it sometime this week.

**Comment by MattSurabian** [comment]
What's the output of `node -v`? Curious if the version of node may have something to do with it as this error doesn't seem at first pass to be Webpack specific.

**Comment by mzgoddard** [comment]
@MattSurabian I believe I've seen this error before. But can't remember if its extract-text or webpack 2 related. So I can't build a test without more from @beckend. (Thanks @MattSurabian for chiming in by the way because you could totally be right.

Node version (and the other deps and versions I mentioned) would still be great but I imagine that info will be in @beckend's mock repo.

**Comment by beckend** [comment]
Thanks for your patience, as I created the mock repo, I reinstalled all deps from scratch...and it worked. Which led me to a google: [issue](http://stackoverflow.com/questions/28486891/uncaught-error-module-did-not-self-register).
So running `npm rebuild` on project root fixed it, sorry for this.

**Comment by mzgoddard** [comment]
Awesome. I'm glad its working. :smile:

And thank you for letting us know what it ended up being and closing the issue.
