### ISSUE TITLE
Strange default directory behavior

### ISSUE THREAD

**Issue by rococode** [mzgoddard/hard-source-webpack-plugin#237]
I'm literally just using `new HardSourceWebpackPlugin();` so I don't think I'm doing anything wrong, but this is what's being generated by the plugin right now:

![](https://i.imgur.com/Utu86Yw.png)

As you can see, it's creating a brand new `node_modules` inside my `src` folder, rather than using my actual `node_modules` folder (which is one level up).

Is this meant to be the default behavior with this folder structure? Seems kind of unusual.

**Comment by mzgoddard** [comment]
@rococode The default creates a cache directory relative to your [webpack context option](https://webpack.js.org/configuration/entry-context/#context). If thats not set it makes the path relative to the current working directory.

So either your context points into src, or you're building from that directory. I think thats fine and hard-source should probably be a little smarter. But I'm not sure if I'll make that change in `0.5.x`, so that may be a bit before the default changes in probably `0.6.x`.

You can work around this by setting `cacheDirectory` in the options to HardSource.

Thanks for opening this issue.
