### ISSUE TITLE
Webpack 2 and Hot module replacement

### ISSUE THREAD

**Issue by thangngoc89** [mzgoddard/hard-source-webpack-plugin#27]
We're migrating to webpack 2 at Phenomic but HMR isn't working for us. Did you test with webpack 2 and HMR ? 

Our branch is here https://github.com/MoOx/phenomic/tree/webpack-2

Our dev-server is an express instance with  webpack-dev-middleware and webpack-hot-middleware 

Behaviours: 

- Route `/**.hot-update.json` not found
- Client doesn't fetch the new hot-update hash correctly. 
   - If I start the dev server, make a change to trigger HMR. Via `/__webpack_hmr` I can see that the new hash for hot-update is A. Client fetches `/A.hot-update.json` but it's a route not found as I said  above.       
   - Next, I make another update and get hash B. Client still fetches `A.hot-update.json`
   - Restart dev server, make a changes, now the client fetches hash B.

**Comment by mzgoddard** [comment]
@thangngoc89 I have tested with webpack 2. I'm not sure if I've tested with webpack 2's hmr. I'll take a look.

**Comment by MoOx** [comment]
Thank you!

**Comment by mzgoddard** [comment]
@thangngoc89 @MoOx I'll have a change up soon that'll fix this.

The problem is HardSource currently runs a pre-compile to detect module's harmony imports and exports changing (cause it means it needs to invalidate the dependency and rebuild it). That pre-compile is interfering with HMR leading it to think no change happened in the build. Cool thing from this I found that webpack 2 adds a new entry point (`need-additional-pass`) to make webpack optionally perform multiple passes. Rewriting the pre-compile into performing an additional pass instead will fix HMR and make HardSource less hacky!

**Comment by thangngoc89** [comment]
@mzgoddard Thank you. You're awesome
