### ISSUE TITLE
Errors: level not found, Can't resolve 'webpack/lib/dependencies/HarmonyCompatiblilityDependency

### ISSUE THREAD

**Issue by drweb86-work** [mzgoddard/hard-source-webpack-plugin#273]
Hello

After adding your cool plugin to my project it failed with errors

ERROR in ./node_modules/hard-source-webpack-plugin/lib/hard-source-leveldb-serializer.js
    Module not found: Error: Can't resolve 'level' in node_modules\hard-source-webpack-plugin\lib'
     @ ./node_modules/hard-source-webpack-plugin/lib/hard-source-leveldb-serializer.js 1:13-29
     @ ./node_modules/hard-source-webpack-plugin/lib/hard-source-leveldb-serializer-plugin.js
     @ ./node_modules/hard-source-webpack-plugin/index.js
     @ dll vendor

    ERROR in ./node_modules/hard-source-webpack-plugin/index.js
    Module not found: Error: Can't resolve 'webpack/lib/dependencies/HarmonyCompatiblilityDependency' in node_modules\hard-source-webpack-plugin'
     @ ./node_modules/hard-source-webpack-plugin/index.js 44:37-104
     @ dll vendor

Thanks.

**Comment by Statfine** [comment]
same as you, have you solve it @drweb86-work

**Comment by mzgoddard** [comment]
@drweb86-work @Statfine Are you compiling hard-source-webpack-plugin with webpack? Are you requiring it from a file that is being built causing hard-source itself to be build?

On the second error (HarmonyCompatibilityDependency) you could update to `hard-source-webpack-plugin@0.6.0`. It no longer has a direct require on the file.

**Comment by Statfine** [comment]
![1519782093016](https://user-images.githubusercontent.com/4608910/36765324-96779ec8-1c6b-11e8-88e8-5cf01a6b4fdf.jpg)
@mzgoddard  same error after update to hard-source-webpack-plugin@0.6.0

**Comment by mzgoddard** [comment]
@Statfine those errors are because you are building hard-source-webpack-plugin into your dll. Why do you need to build hard-source-webpack-plugin into your webpack output? If you need to do that you'll need to set `level`, `module` and `webpack/lib/util/createHash` to be externals (and really probably a lot more modules).

**Comment by Statfine** [comment]
@mzgoddard  My project is based on [https://github.com/react-boilerplate/react-boilerplate](url)；I add this plugin and didn't make any changes

**Comment by mzgoddard** [comment]
@Statfine you need to add `hard-source-webpack-plugin` as a dev dependency. `react-boilerplate` builds all normal dependencies into the dll. If `hard-source-webpack-plugin` is in the dependencies member of package.json it will be built into your application.

`npm install hard-source-webpack-plugin`
or
`yarn add hard-source-webpack-plugin`

will cause the error you are getting.

`npm install --save-dev hard-source-webpack-plugin`
or
`yarn add -D hard-source-webpack-plugin`

will **not** cause that error.

**Comment by AndersonMattjie** [comment]
Same error as index.js 104 unexpected token )

**Comment by mzgoddard** [comment]
@jamalsoueidan This issue related to `hard-source-webpack-plugin` being required by a module in the build. `webpack` is trying to build `hard-source-webpack-plugin` instead of using it as a plugin. That is to say it was a config issue.

@jamalsoueidan @AndersonMattjie indexjs 104 error is using Node 6 with `hard-source-webpack-plugin` `0.7.x`. `0.7.6` adds an engine version check clarifying what was stated in the CHANGELOG that `0.7.x` drops Node 6 support. You can use `0.6.x` with Node 6 if you need to continue using Node 6.
