### ISSUE TITLE
Inavlidate cache when webpack config changes

### ISSUE THREAD

**Issue by pastelsky** [mzgoddard/hard-source-webpack-plugin#43]
Have been looking at this plugin to reduce my team's rebuild times, but was wondering if cache invalidation might be more trouble than it's worth, especially in a medium sized team.

Since this plugin has access to the webpack configuration object, shouldn't it be easy for the plugin to store and compare hashes of the object and invalidate cache automatically?

Agreed that this may not handle all cases - for eg. when you update versions of the plugin, but those change very infrequently compared to  the webpack config

**Comment by SBoudrias** [comment]
Would it be easier to just not load any cache when the watcher starts? Changing versions or the config files requires restarting the webpack watch process already. So if the cache wasn't re-used between runs, then this would be a non-issue no?

Otherwise, I think hashing the content of the config (and why not the one of package.json, or npm-shrinkwrap) would probably works.

From what I understand, right now you can do it yourself using the `configHash` option.

**Comment by mzgoddard** [comment]
@SBoudrias is correct. You can currently do this through the `configHash` option. It can be combined with `[confighash]` being placed in the `cacheDirectory` and `recordsPath` options to support a cache per config. Importantly that helps you use `webpack` and `webpack-dev-server --hot --inline` on the command line with the same config. Those arguments lead to a different config.

Right now `configHash` doesn't come with a default. But you can fill use `node-object-hash` for that. It doesn't use `node-object-hash` as a default because it isn't a good one, though it may the best one. (But I don't want it as a default in case users encounter the cases that it'll fail very confusingly.)

`environmentPaths` gives you a bunch of configuration options. You can hash on an npm shrinkwrap file while disabling the node_modules folder. You can also turn environmentPaths off.

```js
new HardSourceWebpackPlugin({
  cacheDirectory: 'path/to/cache/[confighash]',
  recordsPath: 'path/to/cache/[confighash]/records.json',
  configHash: require('node-object-hash')().hash,
  environmentPaths: false,
}),
```

```js
environmentPaths: {
  directories: [],
  files: ['package.json', 'npm-shrinkwrap.json'],
},
```
