### ISSUE TITLE
recompiling/incremental builds is slower with hard-source

### ISSUE THREAD

**Issue by christiannguyen** [mzgoddard/hard-source-webpack-plugin#479]
Sorry about the lack of information just wanted to know if this was normal or not?

It increases the initial build but a lot (120 seconds -> 15-20 seconds) but it increases our recompile and incremental build by a couple of seconds

without = 1-2 seconds
with= 3-5 seconds

We don't use typescript and we have a monorepo if thats important info.

Just wanted quick advice or any info that states whether this is fine/normal.

**Comment by kadamwhite** [comment]
The purpose of this is to speed up subsequent builds, which I believe includes incremental builds. If that wasn't what you were experiencing then I suspect that is an issue.

Since this is quite old and there's no direct feedback other than "it isn't doing what it's supposed to," which I believe to be echoed by a lot of subsequent tickets, I'm going to close this out.
