### ISSUE TITLE
Support for addContextDependency

### ISSUE THREAD

**Issue by aaronjensen** [mzgoddard/hard-source-webpack-plugin#59]
https://webpack.github.io/docs/loaders.html#addcontextdependency

`addContextDependency` can be used to add an entire directory as a loader's dependency. This is necessary in some cases like [sass-loader](https://github.com/jtangelder/sass-loader/pull/6) or [react-styleguidist](https://github.com/styleguidist/react-styleguidist/pull/242).

hard-source-webpack-plugin doesn't seem to acknowledge directory changes when using this, so purging cache is necessary whenever adding a new component to our styleguide, for example.

**Comment by mzgoddard** [comment]
@aaronjensen Thanks for opening this issue. Looks to me like you're experiencing a bug after the change to use md5s in considering rebuilds. There is a little boolean test that needs to split out testing context timestamps.

`contextDependencies` are supported in HardSource as far as normal webpack supports context dependencies with the memory cache webpack normally uses. They're tracked in the cache but their checked against values that are not created. Any modules with context dependencies check if their dependency has changed and not being to check it defaults to rebuilding. This is because timestamps are loaded for files but not contexts. I don't know the full history but I suspect normal webpack doesn't load context dependency timestamps because the definition of a timestamp for a context is a bit muddled or that performance of building that timestamp could be very large depending on the amount of files in the context.

Once I fix the bug for the time being any modules with context dependencies will always rebuild. The path to changing that isn't immediately clear.

**Comment by aaronjensen** [comment]
@mzgoddard That sounds fine to me. Thank you!

**Comment by aaronjensen** [comment]
Thanks much @mzgoddard, that worked for us.

**Comment by mzgoddard** [comment]
@aaronjensen Glad to hear!
