### ISSUE TITLE
Incompatible with offline-plugin

### ISSUE THREAD

**Issue by ctrlplusb** [mzgoddard/hard-source-webpack-plugin#70]
See https://github.com/ctrlplusb/code-split-component/issues/20

It builds the first time okay, but on second build after cache exists the following error is thrown:

> Error: offline-plugin: Plugin's runtime wasn't added to one of your bundle entries. See this https://goo.gl/YwewYp for details.
    at Compiler.<anonymous> (/Users/foo/bar/baz/node_modules/offline-plugin/lib/index.js:279:20)

**Comment by ctrlplusb** [comment]
This could be an issue with https://github.com/NekR/offline-plugin

**Comment by mzgoddard** [comment]
Thanks @ctrlplusb, this looks like an issue with offline-plugin using a hook in webpack to conveniently track if the the offline runtime is installed. HardSource wants to skip that step since the module is already built.

This will either be fixed by offline-plugin tracking that the offline runtime is installed through a different webpack hook or through me finishing the hard source plugin interface and offline plugin detecting and plugging into hard-source to solve this.

**Comment by ctrlplusb** [comment]
Thanks for looking into this @mzgoddard - and for helping me update my webpack plugin to work with yours.  You are a model citizen of the OSS community. ❤️

**Comment by mzgoddard** [comment]
Fixed as of [`offline-plugin@4.6.0`](https://github.com/NekR/offline-plugin/issues/148#issuecomment-277170882).
