### ISSUE TITLE
Issues in combination with ES modules (Webpack v2, mainFields)

### ISSUE THREAD

**Issue by swernerx** [mzgoddard/hard-source-webpack-plugin#95]
I experienced some heavy problems where my Webpack build was going into some "additional pass" every time I executed Webpack.

As far as I understand HardSource is also reporting a need for an additional pass when it detects changes between the current module and the cached module. The comparison in code looks like:

```js
        var identifier = identifierPrefix + module.identifier();

        var cacheItem = moduleCache[identifier];
        if (cacheItem && (
          !lodash.isEqual(cacheItem.used, module.used) ||
          !lodash.isEqual(cacheItem.usedExports, module.usedExports)
        )) {
```

Interestingly the second comparison is *always* false in my case during the first pass but true in the second pass. After some very long debugging and logging the affected identifiers, I figured out that this issue seems to only affect libraries which are loaded as modern ES2015 modules.

I added these lines into the if-block:

```
          console.log("HARD SOURCE INVALID: ", path.relative(process.cwd(), identifier))
          // console.log("--- USED:",cacheItem.used, module.used)
          console.log("USED EXPORTS:", cacheItem.usedExports, module.usedExports)
```

A typical output in my small demo application looks like:

```
HARD SOURCE INVALID:  node_modules/react-router/es/index.js
USED EXPORTS: [ 'withRouter',
  'matchPath',
  'Switch',
  'StaticRouter',
  'Router',
  'Route',
  'Redirect',
  'Prompt',
  'MemoryRouter' ] true
HARD SOURCE INVALID:  node_modules/lodash-es/isPlainObject.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/react-redux/es/utils/warning.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/react-router/es/Router.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/react-router/es/matchPath.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/lodash-es/_Symbol.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/react-redux/es/components/connectAdvanced.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/react-redux/es/connect/wrapMapToProps.js
USED EXPORTS: [ 'wrapMapToPropsFunc', 'wrapMapToPropsConstant' ] true
HARD SOURCE INVALID:  node_modules/react-redux/es/utils/Subscription.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/react-redux/es/utils/storeShape.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/react-router-dom/es/Link.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/redux/es/compose.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/redux/es/utils/warning.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/history/createBrowserHistory.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/history/createHashHistory.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/history/createMemoryHistory.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/lodash-es/_freeGlobal.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/lodash-es/_getPrototype.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/lodash-es/_objectToString.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/lodash-es/_overArg.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/lodash-es/isObjectLike.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/react-redux/es/connect/mergeProps.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/react-redux/es/connect/selectorFactory.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/react-redux/es/utils/shallowEqual.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/react-router/es/Prompt.js
USED EXPORTS: [ 'default' ] true
HARD SOURCE INVALID:  node_modules/react-router/es/Redirect.js
USED EXPORTS: [ 'default' ] true
```

A pattern you can see is that it seems to only affect files from "es" folder which is typically used for ES2015 modules.

My next step was to disabling usage of ES2015 modules changing the main fields in my Webpack config from:

```js
resolve: { mainFields: [ "web", "browser", "style", "module", "jsnext:main", "main" ] }
```

to

```js
resolve: { mainFields: [ "web", "browser", "style", "main" ] }
```

After doing this change it seems to magically work without doing the previously seen "additional pass".

The question now is basically two:

- Is the comparison with `usedExports` relevant?
- Can we do some special mode for ES modules?
- What part in Webpack is changing the `usedExports` in a way that it breaks HardSource here?

**Comment by swernerx** [comment]
See also: https://github.com/webpack/webpack/issues/4244

**Comment by mzgoddard** [comment]
> Can we do some special mode for ES modules?

This is already the special mode for ES modules. The alternative, "original" support in hard-source for ES modules, is to disable tree shaking (but committing to supporting production builds means that no longer an optimal solution).

> Is the comparison with `usedExports` relevant?

The comparison has to do with webpack's tree shaking and ES module specifier renaming. A bunch of the listed modules in your example are exposing a `default` export. webpack will rename that to `a` if all modules using that module are ES and they `import Name from 'module';` The other possibility is all dependents use `import 'module';` In that case webpack removes the export from the dependency allowing for Uglify or your choice of minifier to remove dead code. `usedExports` is how webpack records if dependents use the exported members of a module.

That bit of code is how hard-source works with modules that changed and if they are now using different exported names. If they are we need to rebuild with an additional pass. We need that rebuild because of the renaming. `usedExports` maps to small names like `'a', 'b', 'c', ...`. Those names like the module ids gets frozen when we cache a module in hard-source currently. To fully thaw we need to rebuild, and to rebuild we need an additional pass, and for that we need to compare `usedExports`.

> What part in Webpack is changing the `usedExports` in a way that it breaks HardSource here?

My first guess is there is a missing test to ensure hard-source is doing its best. As part of that one of hard-source's thawed dependency objects is probably the culprit. `usedExports` is built up from meta data in dependency objects from the modules in the build. If those dependencies are no longer representative we'll get that the extra build which will replace with the original modules and dependencies with the proper set up.

The other possibility and related to the last paragraph is there was a change in the release candidates up and to `2.2.0` that changed some small detail. Not in a bad way, just one hard-source isn't up to date on. We caught a bunch of them. But this one may have slipped through up to this point by being less obvious that the other ones just not building.

**Comment by swernerx** [comment]
Thanks for the clarification. Right now the main problem I have with the rebuild is not the rebuild but the execution of the `done()` plugin API immediately before entering the "additional pass". I reported this in a separate Webpack issue. 

I just figured out that when running server side I get comparable issues to the ES module issue when using specific loaders (babel, css, graphlql). I am not yet sure why this works on client side, but not on server side bundling.

I added some counting mechanism to count valid and invalid items. Most seems to be valid it seems. Example output I see right now:

```
...

>>> INVALID: node_modules/babel-loader/lib/index.js??ref--0-0!/Users/sebastian/Workspace/sebastian-software/advanced-boilerplate/src/server/addFallbackHandler.js
    EXPORTS: [ 'default' ] true

>>> INVALID: node_modules/css-loader/locals.js??ref--2-0!/Users/sebastian/Workspace/sebastian-software/advanced-boilerplate/node_modules/postcss-loader/index.js!/Users/sebastian/Workspace/sebastian-software/advanced-boilerplate/node_modules/sanitize.css/sanitize.css
    EXPORTS: false true

>>> INVALID: node_modules/css-loader/locals.js??ref--2-0!/Users/sebastian/Workspace/sebastian-software/advanced-boilerplate/node_modules/postcss-loader/index.js!/Users/sebastian/Workspace/sebastian-software/advanced-boilerplate/src/app/About.css
    EXPORTS: [ 'default' ] true

>>> INVALID: node_modules/css-loader/locals.js??ref--2-0!/Users/sebastian/Workspace/sebastian-software/advanced-boilerplate/node_modules/postcss-loader/index.js!/Users/sebastian/Workspace/sebastian-software/advanced-boilerplate/src/app/AppContainer.css
    EXPORTS: [ 'default' ] true

>>> INVALID: node_modules/css-loader/locals.js??ref--2-0!/Users/sebastian/Workspace/sebastian-software/advanced-boilerplate/node_modules/postcss-loader/index.js!/Users/sebastian/Workspace/sebastian-software/advanced-boilerplate/src/app/Fonts.css
    EXPORTS: false true

>>> INVALID: node_modules/css-loader/locals.js??ref--2-0!/Users/sebastian/Workspace/sebastian-software/advanced-boilerplate/node_modules/postcss-loader/index.js!/Users/sebastian/Workspace/sebastian-software/advanced-boilerplate/src/app/Home.css
    EXPORTS: [ 'default' ] true

>>> INVALID: node_modules/graphql-tag/loader.js!/Users/sebastian/Workspace/sebastian-software/advanced-boilerplate/src/app/CurrentUser.gql
    EXPORTS: [ 'default' ] true

>>> INVALID: node_modules/json-loader/index.js!/Users/sebastian/Workspace/sebastian-software/advanced-boilerplate/node_modules/yaml-loader/index.js!/Users/sebastian/Workspace/sebastian-software/advanced-boilerplate/src/app/Config.yml
    EXPORTS: [ 'default' ] true

>>> INVALID: node_modules/react-router-dom/index.js
    EXPORTS: [ 'NavLink', 'Switch', 'Route' ] true

>>> INVALID: node_modules/redux-thunk/lib/index.js
    EXPORTS: [ 'default' ] true

VALID #97
INVALID #15
```

I feel that doing rebuilds for getting optimally sliced production builds is okay - when required - I just have issues for optimal developer productivity when doing rebuilds during development.

**Comment by swernerx** [comment]
See also:
https://github.com/webpack/webpack/issues/4244#issuecomment-278943288

**Comment by mzgoddard** [comment]
@swernerx I made a test repo and realized this is because https://github.com/webpack/webpack/issues/4060 was fixed and I had forgotten about that issue. #97 will fix this.

I'm not fully sure I understand the server side issue you are having. Is it possibly a different issue than what is tracked here in #95?
