### ISSUE TITLE
Excluded or optional modules result in failed webpack build

### ISSUE THREAD

**Issue by lzilioli** [mzgoddard/hard-source-webpack-plugin#98]
Great webinar today, it was very informative! Thanks for doing it. I asked a question during it describing the following issue:

I currently exclude Buffer and crypto from my webpack build. I've seen this in various places being recommended to reduce build sizes. I do so with the config:

```javascript
node: {
  Buffer: false,
  crypto: false
}
```

We normally see warnings during our webpack build:

```
WARNING in ./webpack/scripts/third-party/pikaday.js
Module not found: Error: Cannot resolve module 'moment' in /Project/scripts/third-party
 @ ...

WARNING in ./seedrandom.js
Module not found: Error: Cannot resolve module 'crypto' in /Project/node_modules/@scope/seedrandom
@ ...
```

That first warning relates to the `moment` npm package which is an optional dependency of `pikaday`.

We can safely ignore these warnings, as we are confident they do not cause us any problems in production. However, when I pull in this plugin (with the default configs), the warnings turn into hard errors that fail the build.

```
ERROR in ./seedrandom.js
Module not found: Error: Cannot resolve module 'crypto' in /Project/node_modules/@scope/seedrandom
 @ ...

ERROR in ./webpack/scripts/third-party/pikaday.js
Module not found: Error: Cannot resolve module 'moment' in /Project/scripts/third-party
 @ ...
```

I've identified that if I alias these modules to `empty` modules for our development build, the errors go away, but I am worried about shipping such a change because it unnecessarily diverges our production and development builds.

Any advice here?

**Comment by mzgoddard** [comment]
@lzilioli thank you for opening this issue! The good news is this is a very clear bug in hard-source and its support of first-party webpack features. The better news, its pretty easy to fix. Essentially hard-source isn't serializing a dependency attribute called `optional`.

Webpack tracks the blocks that dependencies appear in. If for these cases you have a `require` inside a `try` block, webpack marks it optional, and only warns when it can't be found. Since hard-source isn't serializing the `optional` value, its an error on later runs.

Your really clear ticket made it easy to track down and confirm that its `optional` attribute. I should have a fix up soon.

If you notice anything else off or not working for you please file another issue. That's how we're finding and supporting more of webpack's first party and third party features.

---

As an aside, I think you want crypto in [externals](http://webpack.github.io/docs/configuration.html#externals).

```js
externals: {
  crypto: true,
},
```

crypto isn't one of webpack's [Node shims](http://webpack.github.io/docs/configuration.html#node).

**Comment by lzilioli** [comment]
@mzgoddard Great news. Thanks for the quick response!

**Comment by lzilioli** [comment]
@mzgoddard Tested this fix in my webpack build and it looks good. Thanks again!
